version: '3'

services:
  mongodb:
    container_name: md01
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
    networks:
      - network
  
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.enable-lifecycle'
  #   expose:
  #     - 9090
  #   networks:
  #     - network
    
  telepromo:
    depends_on: [mongodb]
    container_name: tp01
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./telepromo:/project
    networks:
      - network
    command: ['python3', '/project/main.py']

networks:
  network: