version: '3'

services:
  mongodb:
    container_name: md01
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
    networks:
      - network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Mapeamento da porta do host para a porta do container
    networks:
      - network  # Nome da rede que o container vai usar
    volumes:
      - grafana-storage:/var/lib/grafana  # Volume para armazenar dados persistentes do Grafana

  telepromo:
    depends_on: [mongodb, prometheus]
    container_name: tp01
    environment:
      MONGO_URL: "mongodb"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/telepromo
    ports:
      - "9091:9091"
    expose:
      - 9091
    networks:
      - network
    command: ['python3', 'app.py']

networks:
  network:

volumes:
  grafana-storage:  # Definição do volume