{
 "title": "Telepromo Copy",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Products View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New products",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (site) (telepromo_sites_returns_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Entrys",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (telepromo_user_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total products and offers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (result_type) (telepromo_sites_returns_total{result_type!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent to users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "telepromo_user_sents_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "targets": [
    { "expr": "telepromo_new_users_total", "legendFormat": "Total new users" }
   ]
  },
  {
   "title": "Errors by sites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (telepromo_application_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } }
 ]
}