global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'web-scrapper'
    static_configs:
      - targets: ['web-scrapper:9091']

  - job_name: 'chat-bot'
    static_configs:
      - targets: ['chat-bot:9092']